### ISSUE TITLE
Figure out how to filter or subset instances of the Measure class

### ISSUE THREAD

**Issue by trynthink** [trynthink/scout#1]
I have a lingering concern that using a (single) class to define all of the measures will leave us without a way of selecting a subset of the measures on which to perform an analysis. I imagine we'd want to be able to filter on microsegment and filter out data with low data quality rankings. 

There appear to be several candidate approaches, including (this isn't an exhaustive list):
- assigning each measure to lists representing the appropriate group(s) when it is created
- coding measures something like itertools

**Comment by jtlangevin** [comment]
Multiple instances of our measure class are organized into a list, and it appears that these measure instances may be subsetted by attribute via a list comprehension, as shown here: http://stackoverflow.com/questions/17950101/python-subsetting-a-list-according-to-the-attribute.

I am going to close this issue/milestone for now, assuming this works.  I will add a test to "run.py" to be sure.
