### ISSUE TITLE
Support probability distributions in measure definitions

### ISSUE THREAD

**Issue by trynthink** [trynthink/scout#11]
To capture uncertainty in some terms in the measure definitions, we could incorporate support for probability distributions instead of scalar values.

**Comment by jtlangevin** [comment]
"Run.py" now supports multiple user-defined probability distributions around measure performance and cost parameters.  This issue can be closed.

**Comment by jtlangevin** [comment]
Users should be able to assign a probability distribution to measure lifetime as well as performance and cost.  

This issue will be reopened while lifetime distribution support is being added to "run.py".

**Comment by jtlangevin** [comment]
The "run.py" routine now supports the definition of a probability distribution for measure lifetime, including proper handling of measure lifetime, cost and performance distributions in the calculation of measure prioritization metrics.  This issue can be closed again.
