### ISSUE TITLE
Read in modeling start/end years from raw AEO data

### ISSUE THREAD

**Issue by jtlangevin** [trynthink/scout#110]
In a few files, the modeling start/end year is hard coded. Eventually, this should be derived from the AEO raw data, since the start/end year will likely be changed with each new AEO version.

**Comment by trynthink** [comment]
The start and end years should probably flow down from the source AEO data files to the microsegments JSON and the cost/performance/lifetime JSON via the applicable updating codes (e.g., [mseg.py](https://github.com/trynthink/scout/blob/master/mseg.py) and [mseg_techdata.py](https://github.com/trynthink/scout/blob/master/mseg_techdata.py)), and from there, to the measure evaluation schemes in run.py.
