### ISSUE TITLE
Support measures that include fuel switching

### ISSUE THREAD

**Issue by trynthink** [trynthink/scout#12]
Some measures might incorporate fuel switching within a segment, such as replacing a gas cooktop or range with a more efficient induction electric unit. Such measures might require defining two microsegments, corresponding to the incumbent and new fuel types, as well as other supporting information not in traditional measures.

It is also possible that we should support fuel switching by simply defining measures and then instructing the solver/engine to select the appropriate technologies either with or without fuel switching. Incorporating it into the solution step might be inconsistent with the installed cost data in each measure.

**Comment by jtlangevin** [comment]
Address by commit 180a828.
