### ISSUE TITLE
Problem comparing measure unit capital and operating costs in the commercial sector

### ISSUE THREAD

**Issue by jtlangevin** [trynthink/scout#124]
In the commercial sector, a measure's installed cost units must be in either $/1000 CFM (ventilation); $/1000 LM (lighting); and $/kBtu/h (everything else) to allow comparison with EIA baseline installed costs.  This creates problems when trying to compare unit installed costs with unit operating costs for the financial metric calculations, as operating costs in the commercial sector will be in $/ft^2 floor.

To remedy this problem, commercial measure installed cost units should be translated to $/ft^2 floor before proceeding with cost savings and financial metric calculations.

**Comment by trynthink** [comment]
Add new function to com_mseg_tech.py that compares capital cost conversion factors calculated by the function added in 8d89209 to the conversion factors used with the ECMs defined in ./supporting_data/convert_data/ecm_cost_convert.json.

**Comment by jtlangevin** [comment]
Did you actually look at the comparison? I've noticed that some commercial baseline costs seem low. For example, in the 'cpl_res_com_cz.json' file, 'rooftop AC' cost runs about $0.002/ft^2 floor. This would mean a 100K ft^2 floor building only pays $200 for its RTU? That seems more on par with the EIA's RTU cost estimate on a $/kBtu cooling basis, not on a $/unit basis.
