### ISSUE TITLE
RESDBOUT.txt file and documentation missing

### ISSUE THREAD

**Issue by nfette** [trynthink/scout#125]
Regarding the error:
`python mseg.py`
`...`
`IOError: RESDBOUT.txt not found.`

I can't find the documentation for how to obtain or compile the RESDBOUT.txt file. Can you give a hint, please? Thanks.

**Comment by trynthink** [comment]
It's important to note that even the master branch of this repository is still pre-release and thus incomplete. The residential energy use and stock data file (RESDBOUT.txt) and other files that are used to prepare the input JSON databases should be [requested](http://www.eia.gov/about/contact/) from the Energy Information Administration.

A response to this query should be addressed in the documentation when it is updated later this year.

**Comment by trynthink** [comment]
RESDBOUT and the other supporting input data files from EIA are still not available on the repo. That said, they are not needed to run new ECMs, as consolidated JSON databases are now provided (in [supporting_data/](https://github.com/trynthink/scout/tree/master/supporting_data)). These databases include current and projected energy use, equipment stock, housing stock and square footage, and baseline building equipment and component capital cost, energy performance, and service lifetime. Further information on using Scout is available from the documentation (http://scout-bto.rtfd.io).
