### ISSUE TITLE
Write script to update site-source conversions and CO2 emissions data automatically

### ISSUE THREAD

**Issue by trynthink** [trynthink/scout#144]
The CO<sub>2</sub> prices (Social Cost of Carbon) and site to source and CO<sub>2</sub> emissions rates by fuel type derived from the Annual Energy Outlook are currently stored in an input data file. That file is created by copying and pasting data from AEO Excel files and then converting the calculated values into a formatted text or JSON file.

This process should be replaced with code that imports the data at the same time that the other input data JSON files are updated. These data will need to be pulled using the EIA data API since they do not appear in the files from EIA currently used to update the input data JSONs, but moving to code will provide documentation for the calculation methodology and units, and formalize the updating so that those data are not out of sync with the rest of the input data derived from the AEO.

The Social Cost of Carbon data will probably still need to be updated manually since those data are published in a PDF.

**Comment by jtlangevin** [comment]
We should also add a check of the site-source conversions file year range in 'mseg_meta.py'.
