### ISSUE TITLE
Support handling of 'all' within the microsegment subfields of measures

### ISSUE THREAD

**Issue by trynthink** [trynthink/scout#17]
It might be helpful to incorporate the ability to parse "all" for some of the microsegment definition fields in the measures, particularly building type and climate zone. I don't think it would be too difficult to implement, and would make the measure database more readable (if less explicit). I don't know if the lack of specificity of "all" makes this approach problematic or helpful in the long run.

**Comment by jtlangevin** [comment]
As of right now, it seems like a helpful option.  It would certainly make aggregating building types/climate zone micro segments more straightforward, and would also help in cases where we are addressing an entire end use micro segment.  

For example, window efficiency improvements address all heating and cooling energy, so in your measures JSON, "fuel type" and "technology" would be "all", while "end use" would still be a list argument to accommodate both heating/cooling.  Am I understanding that correctly?

**Comment by trynthink** [comment]
Yeah, that's a good example. Another might be a cable set-top box efficiency improvement, which would apply equally to all climate zones. It sounds like a) this capability should be implemented and b) whoever writes the code will need to decide for what categories supporting 'all' makes sense.

**Comment by jtlangevin** [comment]
For the purposes of the Python Engine routine (run.py), it is helpful to leave the definition fields in full list format (e.g. ['AIA_CZ1', 'AIA_CZ2', 'AIA_CZ3', 'AIA_CZ4', 'AIA_CZ5']) - this ensures that the modeler knows exactly what microsegment properties are being represented for each measure.  

The ability for a user to click an 'all' button to generate the above climate zone list would be useful in our web interface for Scout.  However, in the context of our analysis engine development in Python, this issue can be closed.
