### ISSUE TITLE
Generate baseline microsegment performance levels

### ISSUE THREAD

**Issue by trynthink** [trynthink/scout#18]
I believe it is preferred that measures be described with absolute technical performance, e.g. COP, HSPF, kWh, lumens/W, etc. instead of percent energy savings, which is how many measures were defined historically. If measures are defined in absolute terms, to determine the impact of the measure against the baseline, do we then need to define the baseline or stock absolute performance level? 

For example, if we have a measure for "ultrasonic clothes dryers" that uses 56 Wh/load, am I correct in thinking that without knowing the Wh/load performance of the existing stock of clothes dryers, we can't determine the impact of the measure?

If these data are needed to support the tool, it is possible that it belongs in the microsegment database or a companion database with the same structure, not embedded in the measures.

**Comment by jtlangevin** [comment]
Yes, I think this is the correct interpretation.  Ideally, each measure would have clearly defined baselines for cost and performance figures, which should be easier for others to interpret than cost or performance premiums.

I agree it would be useful to create a separate database of measure cost and performance information, which can be mined in the process of filling out each measure for analysis.  Like the micro segments JSON, this separate database could be updated as new information becomes available, and may be a useful source of information in its own right outside the context of P Tool analysis.  

Should we create a new task to develop this separate cost/performance database?

**Comment by trynthink** [comment]
Yes, we should definitely generate these databases. Given the title of this task, I don't think we need to create a separate task to remind us that we'll need to tackle them, but I'll change the labels to indicate that this is an action item and not a question now.

**Comment by jtlangevin** [comment]
We have developed a separate base_costperflife JSON for the residential sector that includes technology performance/cost/lifetime data, much of which is drawn from EIA .txt files.  These data are specified in absolute terms with associated units, as desired in the comments above.  Similar data exist for many commercial sector technologies and will be added in subsequently.  This issue can be closed.
