### ISSUE TITLE
Describe technologies supplanted by measures

### ISSUE THREAD

**Issue by trynthink** [trynthink/scout#19]
In creating the sample measures, I realized we might need to provide some information defining the performance of the products being *replaced* as well as the measures (or replacing products).
* Service lifetime
* Cost

It is possible that this information is only needed for the adoption potential-type simulations.

**Comment by jtlangevin** [comment]
Yes, I believe we will need at least three pieces of baseline information - lifetime, cost, and energy performance.  It is worth noting that while baseline lifetime is static, baseline cost and energy performance could be expected to change over time (as, for example, the cost of a baseline technology is driven down with wider adoption, or the baseline unit efficiency level improves gradually over time).  We can probably handle such dynamics separately from the basic measure definition procedure.   

In the current P Tool, baseline cost and energy are addressed in the "Technical Measure Database" tab (implicitly in some cases), while baseline lifetime is address in the "Market and Sales Data" tab.  In our new version, we should specify all three pieces of baseline information in one place, whether that be the measures JSON, or a separate JSON dedicated to cost/performance information, as discussed in another issue.

**Comment by jtlangevin** [comment]
Baseline residential technology performance/cost/lifetime information is now available in a separate JSON, much of which is populated via EIA data (see issue #54 branch development).  Technology performance/cost/lifetime values cover the modeling time horizon and may change over that time period.  These data also exist for commercial sector technologies.  

This issue/milestone can be closed.
