### ISSUE TITLE
Support both unitized and scalable measures

### ISSUE THREAD

**Issue by trynthink** [trynthink/scout#20]
Some measures relate to unitized devices or technologies, such as induction cooktops or set-top boxes. On the other hand, HVAC technologies in particular come in many sizes. I'm not sure if there's some reason we might need to be able to define a unit size (e.g. 3 ton) for these technologies where the system could be increased or decreased in size for a given installation.

**Comment by jtlangevin** [comment]
Perhaps not a single unit size, but a range of equipment sizes to which our measure cost/performance data applies, where appropriate (i.e., HVAC equipment).  

In these cases, we might specify a single set of cost/performance figures and note in the JSON that they are representative of a certain range of equipment (i.e., energy savings from a 10 ton RTU are used to represent a 10-20 ton RTU range). 

Alternatively, we might use statistical distributions to capture the likely variance in cost/performance across all the equipment sizes addressed by a single measure.

**Comment by jtlangevin** [comment]
Both the approaches mentioned above (using single representative input values and statistical distributions on inputs) are currently supported in the Scout analysis engine. This issue can be closed.
