### ISSUE TITLE
Using Energy Plus as Energy Performance Source??

### ISSUE THREAD

**Issue by suidi1990** [trynthink/scout#206]
Hi!
I'm new to Scout, and am trying to use EnergyPlus instead of the simple input for measuring Energy Performance. I break it down to different building types and construction types, and only doing it for zone 1 and lighting (see the pic below for inputs), But when I run the ecm_prep, it gave me those errors (see pic below). I'm guessing it's because I need to put some external E+ simulation files or results in the scout folder, but not sure how to do it (or if it's what causes the error). If anyone can help me with it, or let me know if there's any detailed instruction on how to do it with E+, that will be great! Thanks!
![image](https://user-images.githubusercontent.com/42154516/43738179-5e10b024-9989-11e8-8b61-aa931e522dea.png)
![image](https://user-images.githubusercontent.com/42154516/43738002-d26b2fae-9988-11e8-8e75-ece9950ea179.png)

**Comment by jtlangevin** [comment]
@suidi1990 Thanks for diving into the Scout web UI and for bringing this issue to our attention.

You've uncovered a gap between the current capabilities of the UI and the current capabilities of the analysis engine. While the UI allows this 'EnergyPlus' Value Type, as you noted the user must provide supporting EnergyPlus simulation results in a certain format (you can see examples in the [./ecm_definitions/energyplus_data](https://github.com/trynthink/scout/tree/master/ecm_definitions/energyplus_data) folder off the root Scout directory). Unfortunately, we do not yet provide users with the supporting documentation/code needed to generate these data in the correct format for their own custom analyses. Accordingly, the use of EnergyPlus as an ECM performance source is not supported at this time.

To address this issue in the near term, we can make it clearer in the UI documentation that the 'EnergyPlus' Value Type is currently unsupported, though it will be in a future Scout version. We will also modify 'ecm_prep.py' to generate a more informative error message in the case that a user still attempts to use the 'EnergyPlus' Value Type.

In the longer term (~next year), we plan to finishing adding support for this ECM feature. In the meantime, many thanks for your patience and feedback.

**Comment by suidi1990** [comment]
Hi Jared,

Thanks for the clarification! I will just use points and put in the saving
numbers based on Energy+ simulation results.
I have another small question so can I just ask you through this email?
I'm trying to generate an ECM that function as an occupancy sensor, which
will control the thermostat to turn it to unoccupied mode to when there's
no people in the area. I'm wondering if it should be applied to end use
"heating" and "cooling" with technologies of all plants, or to end use
"ventilation" with the technologies of, for example, "VAV"?
Thanks for your help!

Di

**Comment by jtlangevin** [comment]
Hi Di,

Sounds good. Regarding your question, I would set up your ECM to mimic the
EnergyPlus simulation setup you're working with as closely as possible.

For example, if your EPlus results show 25% heating and 15% cooling savings
in large offices, you would set the 'Building Type' parameter in step 2 of
the Add New ECM form to 'Commercial' -> 'Large Office,' the 'End Use'
parameter to heating and cooling, the 'Technology' option to 'all,' and
then use the detailed performance input option in step 4 to separately
specify energy performance for each of the heating and cooling end uses as
the appropriate relative savings percentage.

For ventilation, if you were only running EPlus simulations on buildings
with VAV, then yes, you'd want to select 'VAV' as the 'Technology' option
in step 2. Note, however, that you would then also need to use the 'Market
Scaling Fraction' option in step 7 of the ECM form to restrict applicable
heating and cooling energy use markets to only those buildings with a VAV
system type (you can derive the percentage of buildings with VAV/CAV from
CBECS <https://www.eia.gov/consumption/commercial/>). The detailed input
selections in step 7 would then look something like the attached PDF (note
that 0.5 is a made up scaling value).

It really depends how detailed you want to get. It might make sense to
start with a simple representation (each of the heating, cooling, and
ventilation end uses is reduced by a certain percentage across all
technologies) and go from there.

Best wishes,

Jared

**Comment by suidi1990** [comment]
Hi Jared,

Hopefully I can still reach you through this email. I have a Scout related
question and can't find the forum website to submit a ticket for this. I'm
just wondering if the Scout can estimate the energy savings for a certain
state instead of for the whole climate zone.
Please let me know if I need to submit a ticket for this through the
certain website and it'll be great if you can direct me to it.

Thank you and have a great day,
Di
