### ISSUE TITLE
Add validation for ECM input in ecm_setup.py

### ISSUE THREAD

**Issue by lzavod** [trynthink/scout#214]
When a Scout input is represented incorrectly in either a standard ECM or a Package ECM, the program crashes in python with a message that doesn't point to the input problem.  

Can you include ECM input validation in ecm_setup.py?

**Comment by jtlangevin** [comment]
@lzavod do you mean add ECM input validation in 'ecm_prep.py'? 

We already have input validation in that module, so it would be helpful to know the details of your case to reproduce the issue. Could you attach JSON(s) for the ECM/ECM package you ran that caused the program to crash? Thanks.

**Comment by jtlangevin** [comment]
Closing this due to lack of response and because we already have input validation in ecm_prep.py. Can reopen if further information comes to light.
