### ISSUE TITLE
Plotting output fails. Unable to find package called "farver"

### ISSUE THREAD

**Issue by zberquist** [trynthink/scout#229]
Hello,

I believe I accurately followed all necessary steps in the tutorial, and I have made no edits to any of the files. But when I run Scout, I get this error that prevents any of the PDFs from being generated so I can't look at many of the plots. Has anyone come across this?

Thanks

**Comment by jtlangevin** [comment]
@zberquist this is an issue with the R plotting routine. Can you let us know what version of R and operating system you are using?

**Comment by zberquist** [comment]
Thanks for the quick response!

R x64 4.0.3 on Windows 10 64-bit

**Comment by trynthink** [comment]
@zberquist Have you tried manually installing `farver` to see if that resolves the issue? The `scales` package depends on `farver`, but for whatever reason, when `scales` was installed, its dependencies were not installed (successfully).

**Comment by zberquist** [comment]
Should I download farver and just replace that folder in the R-folder?

Thanks

**Comment by jtlangevin** [comment]
@zberquist what about opening R and typing install.packages("farver"), selecting a mirror and installing, then typing library("farver")?

**Comment by zberquist** [comment]
@jtlangevin That worked! I can now see all the plots!! Thank you so much
