### ISSUE TITLE
Implement ability to group measures together

### ISSUE THREAD

**Issue by trynthink** [trynthink/scout#23]
Each measure should be elemental, that is, they should not combine multiple efficiency improvements or multiple technologies. Rather, it should be possible for the user to join or link multiple measures together for staging purposes, while keeping each measure separate and specific. 

Put another way, to consider the effect of measures A, B, and C, as well as combinations of the three, one would need to create measures for each of the combinations of the three, for a total of seven measures (A, B, C, AB, BC, AC, ABC). This requirement creates a chance for errors to be introduced; if A has a mistake, it is possible that measure A will be updated but measures AB, AC, and ABC could be missed. Trying to impose a requirement on users to carefully check all other measures when applying corrections is not a sustainable long-term strategy. Instead, by allowing users to define groups of measures, when one measure is updated, all of the groups using that measure will be updated as well.

**Comment by jtlangevin** [comment]
Addressed by commit 089cf8a
