### ISSUE TITLE
ecm_prep.py feature - add command line options for scripting what are currently interactive options

### ISSUE THREAD

**Issue by dewittpe** [trynthink/scout#244]
I would be nice to be able to specify the value for options in `ecm_prep.py`

For example, with the `--alt_regions` flag specified an interactive specification for the defining the `region` is required.  This is a nuisance for scripting.

I propose two options to allow easy scripting

1. Add an additional command line variable, in this case `--alt_regions_breakdown` which is an integer value.  This argument would be ignored if `--alt_regions` is not specified.  A default value for `--alt_regions_breakdown` of zero would allow for the existing interactive behavior.  Users could call `python ecm_prep.py --alt_regions --alt_regions_breakdown=1` to specify EMM without interactive specification.

2. Refactor `--alt_regions`, and similar arguments, to be integer value.  If not specified no change in behavior.  If specified without a value the default would require the existing interactive specification, else, specified with a value would attempt to set the needed value with the interactive input being used if input is invalid.

While option 1 increases the number of commands it will be the easiest to integrate into the existing code base.

**Comment by dewittpe** [comment]
Additional consideration might be needed for the inputs with two or more values such as `exog_hp_rates` and `retro_set`

**Comment by jtlangevin** [comment]
@dewittpe option 2 sounds more concise; we'd just need to manage any downstream effects as later parts of the code will expect string values for these options in their processing.

**Comment by dewittpe** [comment]
> @dewittpe option 2 sounds more concise; we'd just need to manage any downstream effects as later parts of the code will expect string values for these options in their processing.

I agree option 2 would be preferable.  Managing downstream impacts will take some effort.  Not only strings, but the change from logicals to integers will need to be addressed too.  My initial thought is a default value of -1 which would be the same as `False`.  If specified without a value the default would be `0` to go to interactive mode, and then users can specify 1, 2, 3, ... for specific options.  

This seems like a good option for end users, but an insane set up for commonly interchanges for integer values and logicals.  

I'm also only thinking of the inputs that are singletons.  I think there are some which are arrays, which may be need more design thoughts.

Would deprecating the interactive mode be preferable?  Then a default integer value of 0 for `False` and specific values of 1, 2, .... for the noted options.

**Comment by jtlangevin** [comment]
@dewittpe re your comment about it being `insane` for common interchanges, can you expand? 

I'm reluctant to give up the interactive feature entirely b/c I think it's helpful for users, particularly those who aren't very familiar with those options. OTOH I see the benefits of being able to script runs in batch using variations on those options, which is why your option 2 sounded appealing. But if you think it's ultimately not good practice from a data exchange perspective, we should think about alternatives.

**Comment by dewittpe** [comment]
Commonly mapping between boolean and integer values: 0 = False, 1 = True.  My initial idea of -1 as False, 0 as interactive, 1, 2, 3, ... for options seems dangerous as 0 is lumped into a True state.   Although, the more I think about this, maybe the structure shouldn't be an integer, just a string.   A value of `I` as the default for interactive, and then digits for options.

A design issue I'm thinking through is how to handle the options well.  Noting that some of the args get updated from boolean to strings makes it difficult for me to think of a good set of changes without a major refactor.

two examples:

1. [opts.adopt_scn_restrict](https://github.com/trynthink/scout/blob/e61f7e6ca65b307242d0262bad14d671799cb296/ecm_prep.py#L10956) is a boolean.  If it is True, then it will be changed to a string.  
2. [opts.grid_decarb](https://github.com/trynthink/scout/blob/e61f7e6ca65b307242d0262bad14d671799cb296/ecm_prep.py#L11104) is similar.

**Comment by aspeake** [comment]
Fixed in https://github.com/trynthink/scout/pull/297 and will be further improved with https://github.com/trynthink/scout/pull/355
