### ISSUE TITLE
Capture interactions between microsegments from some measures

### ISSUE THREAD

**Issue by trynthink** [trynthink/scout#26]
Some measures, while they might apply to a set of microsegments, can also have interaction effects on other microsegments. As an example, a measure for LED bulbs is a lighting measure and should be coded as impacting the appropriate lighting microsegments. At the same time, replacing fluorescent or incandescent bulbs with solid-state LED bulbs will also reduce cooling load and increase heating load. These interactions need to be captured. They should probably be included in the model itself, and not be coded into the measure definition, as that would require that individuals creating measures accurately note the relevant interactions for that particular measure, and might create an opportunity for errors (e.g. if someone forgets to code for changes in both heating _and_ cooling from a lighting-specific measure).

**Comment by jtlangevin** [comment]
The secondary end use effects of a measure may now be directly specified by users in the measure's definition.  In the case of commercial lighting, if a user has not specified these secondary end use effects they will be automatically added in using relevant thermal load components data on the waste heat generated by commercial lighting.
