### ISSUE TITLE
ecm_prep.py fails on clean clone of v0.8

### ISSUE THREAD

**Issue by dewittpe** [trynthink/scout#273]
After removing the ecm_prep.json file to make sure all the ecms and ecm_prep.py code would be evaluated I get the following: 

![image](https://user-images.githubusercontent.com/3136617/189175582-2b892320-fa51-4762-abdb-618de3f33407.png)

I would expect the default settings to work and an not require the end user to select alternative inputs.

**Comment by jtlangevin** [comment]
Let's close this and retain #273, which gets at the real issue here.
