### ISSUE TITLE
installation file missing

### ISSUE THREAD

**Issue by bttrpntng** [trynthink/scout#284]
I had problems installing Scout from the given directions so I had a programmer friend help me out. He said the
run.setup.json
file needed to run the program was missing. 
Please supply the file with clear easy directions on how and where to install it.

**Comment by bttrpntng** [comment]
The file isn't in Scout

Python 3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 
64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

======= RESTART: 
C:\Users\user\Downloads\Scout-0.8\scout-0.8\run_setup.py ======

This function will help configure the simulation. Respond to each of the 
prompts.
Hit "enter" or "return" to skip a question.

Traceback (most recent call last):
   File "C:\Users\user\Downloads\Scout-0.8\scout-0.8\run_setup.py", line 
659, in <module>
     main()
   File "C:\Users\user\Downloads\Scout-0.8\scout-0.8\run_setup.py", line 
618, in main
     with open(ref.setup_file, 'r') as fobj:
FileNotFoundError: [Errno 2] No such file or directory: 'run_setup.json'

Yours for Better Looking Longer Lasting Results,

Tim Hoeffel
Better Painting & Coatings
719-641-5043

On 31.1.2023 9:46 am, Jared Langevin wrote:

> @bttrpntng [1] run_setup.json is created as part of the process of 
> running a Scout analysis as described in the Quick Start Guide [2].
> 
> Can you provide more information about where in those steps you are 
> getting hung up and what (if any) errors you are seeing? Thanks.
> 
> --
> Reply to this email directly, view it on GitHub [3], or unsubscribe 
> [4].
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>


Links:
------
[1] https://github.com/bttrpntng
[2] https://scout-bto.readthedocs.io/en/latest/quick_start_guide.html
[3] 
https://github.com/trynthink/scout/issues/284#issuecomment-1410720563
[4]

**Comment by jtlangevin** [comment]
@bttrpntng looks like you are running step 5 of the Guide.l, the run_setup module. Did you run the previous steps? Those steps need to be run first for step 5 to work - in particular, step 4 prepares the missing file you are referencing.

**Comment by bttrpntng** [comment]
I've looked at the long list of requirements for setting up Scout in 
Windows 10. Isn't there a simple setup.exe file that takes care of 
installation? I'm not a coder and all this command prompt stuff is 
confusing and difficult. Can I get the same results using the program on 
the web site?

Yours for Better Looking Longer Lasting Results,

Tim Hoeffel
Better Painting & Coatings
719-641-5043

On 31.1.2023 9:46 am, Jared Langevin wrote:

> @bttrpntng [1] run_setup.json is created as part of the process of 
> running a Scout analysis as described in the Quick Start Guide [2].
> 
> Can you provide more information about where in those steps you are 
> getting hung up and what (if any) errors you are seeing? Thanks.
> 
> --
> Reply to this email directly, view it on GitHub [3], or unsubscribe 
> [4].
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>


Links:
------
[1] https://github.com/bttrpntng
[2] https://scout-bto.readthedocs.io/en/latest/quick_start_guide.html
[3] 
https://github.com/trynthink/scout/issues/284#issuecomment-1410720563
[4]

**Comment by aspeake** [comment]
I believe this is corrected with https://github.com/trynthink/scout/pull/347, @jtlangevin can this be closed?
