### ISSUE TITLE
GitHub Actions need to be updated to newer versions

### ISSUE THREAD

**Issue by trynthink** [trynthink/scout#350]
https://github.com/trynthink/scout/blob/master/.github/workflows/tests.yml currently uses several outdated actions that should be updated to the latest versions.

* actions/checkout@v2 :arrow_right: [actions/checkout@v4](https://github.com/marketplace/actions/checkout)
* actions/setup-node@v2 :arrow_right: [actions/setup-node@v3](https://github.com/marketplace/actions/setup-node-js-environment)
* actions/setup-python@v2 :arrow_right: [actions/setup-python@v4](https://github.com/marketplace/actions/setup-python)

**Comment by trynthink** [comment]
@aspeake Did you have an expectation of when this would get closed? Does it matter whether or not it is completed before #349 or other forthcoming PRs?

**Comment by aspeake** [comment]
> @aspeake Did you have an expectation of when this would get closed? Does it matter whether or not it is completed before #349 or other forthcoming PRs?

I guess I was expecting to do it once the other two open PRs were done, but probably no real reason to do so given the small change. I can update for the release.
