### ISSUE TITLE
Update social cost of carbon

### ISSUE THREAD

**Issue by trynthink** [trynthink/scout#371]
EPA released revised social cost of carbon projections in December 2023. The reports can be found [here](https://www.epa.gov/environmental-economics/scghg). Table A.5.1 in the [Supplementary Material](https://www.epa.gov/system/files/documents/2023-12/epa_scghg_2023_report_final.pdf) includes annual social cost of carbon values as a function of discount rate for 2020–2080.

The social cost of carbon in site_source_co2_conversions*.json should be updated.

**Comment by jtlangevin** [comment]
Also update the CPI values.
